task_name: "expression/pert-prediction-tahoe-regression"
dose: 10.0
emb_name: "random"

hydra:
  sweeper:
    max_batch_size: 20
    params:
      +fold_id: 0,1,2,3,4
      +cell_line: "'CVCL_0023'"
      +estimator_name: "'context mean','no change'"
