task_name: "expression/pert-prediction-sciplex3-regression"
lpm_source_path: "lpm_paper10_ft_morgan_learned_fixmol_best_embeddings/sciplex"
lpm_source_format: "lpm_export"
lpm_restriction_path: "lpm_paper10_ft_morgan_learned_fixmol_best_embeddings/sciplex"
lpm_restriction_format: "lpm_export"
heldout_molecules_path: "lpm_paper10_ft_morgan_learned_fixmol_best_embeddings/heldout_molecules.tsv"
submission_root: "benchmark/submissions_sciplex_lfc_heldout_molecules"

hydra:
  sweeper:
    max_batch_size: 20
    params:
      +cell_line: "'MCF7','A549','K562'"
      +emb_name: "
        'morgan_initialized_lpm',
        'random',
        'pca',
        'ECFP:2_pkl',
        'ChemBERTa-77M-MLM',
        'ChemBERTa-77M-MTR',
        'avalon',
        'cats2D',
        'cats3D',
        'chatgpt',
        'erg',
        'fcfp',
        'maccs',
        'secfp',
        'topological'"
      +estimator_name: "'knn','lasso'"
